public class AddressPractice {
    public void homeAddress(){
        string name = 'Vitap';
        system.debug('name = ' + name);
        integer noOfMembers = 16;
        system.debug('noOfMembers = ' + noOfMembers);
        string houseName = 'Vitap Villa';
        system.debug('houseName ' + houseName);
        integer houseNumber = 18;
        system.debug('houseNumber ' + houseNumber);
        string streetName = 'Ghatlodia';
        system.debug('streetName ' + streetName);
        string cityName = 'Ahmedabad'; //heritage city
        system.debug('cityName = ' + cityName);
        string stateName = 'Gujarat';//India PM (Modi)
        system.debug('stateName ' + stateName);
        string stateISO = 'GJ';
        system.debug('stateISO ' + stateISO);
        string countryName = 'India';
        system.debug('countryName ' + countryName);
        string countryISO = 'IND';
        system.debug('countryISO ' + countryISO);
        string zipCode = '380061';
        system.debug('zipCode ' + zipCode);
        Boolean currentHome = true;
        system.debug('currentHome ' + currentHome);
    }
}
