public class PrimitiveDataTypeDemo2 {
    public void print1(){
        //this is method body.
        Id id1 = '0015i00000BFSCtAAP';
        system.debug('print id = ' + id1);

        //Object --> Object is a parent class to all primitive data types, sOjbects, custom classes and everything in apex
        Object obj1 = 'This is a string';
        Object obj2 = 15;
        Object obj33454 = '0015i00000BFSCtAAP';
        Object obj4 = true;

        system.debug('obj1 = ' + obj1);
        system.debug('obj2 = ' + obj2);
        system.debug('obj33454 = ' + obj33454);
        system.debug('obj4 = ' + obj4);

    }
}
