Map<string, email_domain__mdt> allEmailDomains = email_domain__mdt.getAll();
system.debug(allEmailDomains);


{
    
Gmail=
Email_Domain__mdt:{Domain__c=Gmail, Label=Gmail, MasterLabel=Gmail, Language=en_US, QualifiedApiName=Gmail, Id=m005i000000RUpG, DeveloperName=Gmail, NamespacePrefix=null}, 

hotmail=Email_Domain__mdt:{Domain__c=hotmail, Label=hotmail, MasterLabel=hotmail, Language=en_US, QualifiedApiName=hotmail, Id=m005i000000RUpL, DeveloperName=hotmail, NamespacePrefix=null}

}