OperationsHelper op = new OperationsHelper();
decimal opMax = op.largestOutOfTwoNumbers(74.78, 74.78);
system.debug(opMax);

Decimal opMin = op.smallestOutOfThreeNumbers(7.99, 7.98, 7.97);
system.debug(opMin);

Decimal sum11 = op.sumOfPositiveInteger(-11);
system.debug(sum11);

Integer sum = op.sumOfPositiveInteger(50);
system.debug('sum of 1 to 50 = ' + sum);

integer num = 400;
integer NUM = 4500;
integer nUm = 4500;

system.debug(x);
system.debug(X);